// lib/src/countries.dart
// ISO 3166-1 国家与地区资料。
// 国家语言关联只引用 languages.dart 中已经存在的 LanguageConfig 代码。

import 'languages.dart';
import 'country_language_config.dart';

class CountryConfig {
  final String code;
  final String alpha3;
  final String numericCode;
  final Map<String, String> names;

  /// 这个国家使用的语言代码。
  ///
  /// 保留这个字段，旧的两百多个国家配置不用全部重写。
  final List<String> languageCodes;

  /// 国家专属语言配置。
  ///
  /// 只需要写与全球 LanguageConfig 不同的部分，
  /// 例如这个国家实际使用哪些方言。
  final List<CountryLanguageConfig>
      languageRelations;

  const CountryConfig({
    required this.code,
    required this.alpha3,
    required this.numericCode,
    required this.names,
    this.languageCodes = const [],
    this.languageRelations = const [],
  });

  /// 默认中文名称。
  String get name => nameOf('zh');

  /// 国家实际使用的语言关系。
  ///
  /// languageRelations 会覆盖同一 languageCode 的默认关系。
  List<CountryLanguageConfig>
      get countryLanguages {
    final overrideMap = {
      for (final relation
          in languageRelations)
        relation.languageCode
            .toLowerCase(): relation,
    };

    final result =
        <CountryLanguageConfig>[];

    for (final languageCode
        in languageCodes) {
      final normalizedCode =
          languageCode.toLowerCase();

      result.add(
        overrideMap.remove(
              normalizedCode,
            ) ??
            CountryLanguageConfig(
              languageCode:
                  languageCode,
            ),
      );
    }

    // 允许关系配置中出现 languageCodes 里没有的新语言。
    result.addAll(overrideMap.values);

    return List.unmodifiable(result);
  }

  /// 兼容原来的 country.languages。
  ///
  /// 普通页面只需要 LanguageConfig 时继续使用它。
  List<LanguageConfig> get languages {
    return countryLanguages
        .map(
          (relation) =>
              relation.language,
        )
        .whereType<LanguageConfig>()
        .toList(growable: false);
  }

  /// 根据两位国家代码生成 Emoji 国旗。
  String get flag {
    final upperCode = code.toUpperCase();

    if (upperCode.length != 2) {
      return '🌐';
    }

    return String.fromCharCodes(
      upperCode.codeUnits.map((unit) => unit + 127397),
    );
  }

  String _normalizeUiCode(String uiLangCode) {
    final normalized = uiLangCode.toLowerCase().trim();

    if (normalized.contains('-')) {
      return normalized.split('-').first;
    }

    if (normalized.contains('_')) {
      return normalized.split('_').first;
    }

    return normalized;
  }

  String nameOf(String uiLangCode) {
    final uiCode = _normalizeUiCode(uiLangCode);

    return names[uiCode] ?? names['en'] ?? names['zh'] ?? code;
  }

  /// 搜索国家代码和所有已保存的国家名称。
  bool matches(String keyword) {
    final query = keyword.trim().toLowerCase();

    if (query.isEmpty) {
      return true;
    }

    if (code.toLowerCase().contains(query) ||
        alpha3.toLowerCase().contains(query) ||
        numericCode.contains(query)) {
      return true;
    }

    return names.values.any((name) => name.toLowerCase().contains(query));
  }

  static final Map<String, CountryConfig> _countriesByCode = {
    for (final country in allCountries) country.code.toUpperCase(): country,
    for (final country in allCountries) country.alpha3.toUpperCase(): country,
  };

  /// 同时支持 MY 和 MYS 这类 alpha-2 / alpha-3 查询。
  static CountryConfig? findByCode(String code) {
    return _countriesByCode[code.trim().toUpperCase()];
  }

  /// 按当前界面语言的国家名称排序。
  static List<CountryConfig> sortedBy(String uiLangCode) {
    final result = List<CountryConfig>.of(allCountries);

    result.sort((a, b) => a.nameOf(uiLangCode).compareTo(b.nameOf(uiLangCode)));

    return List<CountryConfig>.unmodifiable(result);
  }

  static const List<CountryConfig> allCountries = [
    CountryConfig(
      code: 'AD',
      alpha3: 'AND',
      numericCode: '020',
      names: {
        'zh': '安道尔',
        'en': 'Andorra',
        'ms': 'Andorra',
        'vi': 'Andorra',
        'ru': 'Андорра',
      },
      languageCodes: ['ca', 'es', 'fr'],
    ),
    CountryConfig(
      code: 'AE',
      alpha3: 'ARE',
      numericCode: '784',
      names: {
        'zh': '阿拉伯联合酋长国',
        'en': 'United Arab Emirates',
        'ms': 'Emiriah Arab Bersatu',
        'vi': 'Các Tiểu Vương quốc Ả Rập Thống nhất',
        'ru': 'ОАЭ',
      },
      languageCodes: ['ar', 'en', 'ml', 'ps', 'fa'],
    ),
    CountryConfig(
      code: 'AF',
      alpha3: 'AFG',
      numericCode: '004',
      names: {
        'zh': '阿富汗',
        'en': 'Afghanistan',
        'ms': 'Afghanistan',
        'vi': 'Afghanistan',
        'ru': 'Афганистан',
      },
      languageCodes: ['fa', 'ps', 'uz', 'tk', 'ug', 'kk'],
    ),
    CountryConfig(
      code: 'AG',
      alpha3: 'ATG',
      numericCode: '028',
      names: {
        'zh': '安提瓜和巴布达',
        'en': 'Antigua & Barbuda',
        'ms': 'Antigua dan Barbuda',
        'vi': 'Antigua và Barbuda',
        'ru': 'Антигуа и Барбуда',
      },
      languageCodes: ['en', 'pt'],
    ),
    CountryConfig(
      code: 'AI',
      alpha3: 'AIA',
      numericCode: '660',
      names: {
        'zh': '安圭拉',
        'en': 'Anguilla',
        'ms': 'Anguilla',
        'vi': 'Anguilla',
        'ru': 'Ангилья',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'AL',
      alpha3: 'ALB',
      numericCode: '008',
      names: {
        'zh': '阿尔巴尼亚',
        'en': 'Albania',
        'ms': 'Albania',
        'vi': 'Albania',
        'ru': 'Албания',
      },
      languageCodes: ['el', 'mk'],
    ),
    CountryConfig(
      code: 'AM',
      alpha3: 'ARM',
      numericCode: '051',
      names: {
        'zh': '亚美尼亚',
        'en': 'Armenia',
        'ms': 'Armenia',
        'vi': 'Armenia',
        'ru': 'Армения',
      },
      languageCodes: ['hy', 'ku'],
    ),
    CountryConfig(
      code: 'AO',
      alpha3: 'AGO',
      numericCode: '024',
      names: {
        'zh': '安哥拉',
        'en': 'Angola',
        'ms': 'Angola',
        'vi': 'Angola',
        'ru': 'Ангола',
      },
      languageCodes: ['pt', 'ln'],
    ),
    CountryConfig(
      code: 'AQ',
      alpha3: 'ATA',
      numericCode: '010',
      names: {
        'zh': '南极洲',
        'en': 'Antarctica',
        'ms': 'Antartika',
        'vi': 'Nam Cực',
        'ru': 'Антарктида',
      },
    ),
    CountryConfig(
      code: 'AR',
      alpha3: 'ARG',
      numericCode: '032',
      names: {
        'zh': '阿根廷',
        'en': 'Argentina',
        'ms': 'Argentina',
        'vi': 'Argentina',
        'ru': 'Аргентина',
      },
      languageCodes: ['es', 'en', 'cy', 'gn'],
    ),
    CountryConfig(
      code: 'AS',
      alpha3: 'ASM',
      numericCode: '016',
      names: {
        'zh': '美属萨摩亚',
        'en': 'American Samoa',
        'ms': 'Samoa Amerika',
        'vi': 'Samoa thuộc Mỹ',
        'ru': 'Американское Самоа',
      },
      languageCodes: ['sm', 'en'],
    ),
    CountryConfig(
      code: 'AT',
      alpha3: 'AUT',
      numericCode: '040',
      names: {
        'zh': '奥地利',
        'en': 'Austria',
        'ms': 'Austria',
        'vi': 'Áo',
        'ru': 'Австрия',
      },
      languageCodes: ['de', 'hr', 'sl', 'hu', 'en', 'fr', 'it'],
    ),
    CountryConfig(
      code: 'AU',
      alpha3: 'AUS',
      numericCode: '036',
      names: {
        'zh': '澳大利亚',
        'en': 'Australia',
        'ms': 'Australia',
        'vi': 'Australia',
        'ru': 'Австралия',
      },
      languageCodes: ['en', 'zh', 'it'],
    ),
    CountryConfig(
      code: 'AW',
      alpha3: 'ABW',
      numericCode: '533',
      names: {
        'zh': '阿鲁巴',
        'en': 'Aruba',
        'ms': 'Aruba',
        'vi': 'Aruba',
        'ru': 'Аруба',
      },
      languageCodes: ['nl', 'en'],
    ),
    CountryConfig(
      code: 'AX',
      alpha3: 'ALA',
      numericCode: '248',
      names: {
        'zh': '奥兰群岛',
        'en': 'Åland Islands',
        'ms': 'Kepulauan Aland',
        'vi': 'Quần đảo Åland',
        'ru': 'Аландские о-ва',
      },
      languageCodes: ['sv'],
    ),
    CountryConfig(
      code: 'AZ',
      alpha3: 'AZE',
      numericCode: '031',
      names: {
        'zh': '阿塞拜疆',
        'en': 'Azerbaijan',
        'ms': 'Azerbaijan',
        'vi': 'Azerbaijan',
        'ru': 'Азербайджан',
      },
      languageCodes: ['ku'],
    ),
    CountryConfig(
      code: 'BA',
      alpha3: 'BIH',
      numericCode: '070',
      names: {
        'zh': '波斯尼亚和黑塞哥维那',
        'en': 'Bosnia & Herzegovina',
        'ms': 'Bosnia dan Herzegovina',
        'vi': 'Bosnia và Herzegovina',
        'ru': 'Босния и Герцеговина',
      },
      languageCodes: ['bs', 'hr', 'sr', 'en'],
    ),
    CountryConfig(
      code: 'BB',
      alpha3: 'BRB',
      numericCode: '052',
      names: {
        'zh': '巴巴多斯',
        'en': 'Barbados',
        'ms': 'Barbados',
        'vi': 'Barbados',
        'ru': 'Барбадос',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'BD',
      alpha3: 'BGD',
      numericCode: '050',
      names: {
        'zh': '孟加拉国',
        'en': 'Bangladesh',
        'ms': 'Bangladesh',
        'vi': 'Bangladesh',
        'ru': 'Бангладеш',
      },
      languageCodes: ['bn', 'en', 'my'],
    ),
    CountryConfig(
      code: 'BE',
      alpha3: 'BEL',
      numericCode: '056',
      names: {
        'zh': '比利时',
        'en': 'Belgium',
        'ms': 'Belgium',
        'vi': 'Bỉ',
        'ru': 'Бельгия',
      },
      languageCodes: ['nl', 'fr', 'de', 'en', 'wa'],
    ),
    CountryConfig(
      code: 'BF',
      alpha3: 'BFA',
      numericCode: '854',
      names: {
        'zh': '布基纳法索',
        'en': 'Burkina Faso',
        'ms': 'Burkina Faso',
        'vi': 'Burkina Faso',
        'ru': 'Буркина-Фасо',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'BG',
      alpha3: 'BGR',
      numericCode: '100',
      names: {
        'zh': '保加利亚',
        'en': 'Bulgaria',
        'ms': 'Bulgaria',
        'vi': 'Bulgaria',
        'ru': 'Болгария',
      },
      languageCodes: ['en', 'ru', 'tr', 'de'],
    ),
    CountryConfig(
      code: 'BH',
      alpha3: 'BHR',
      numericCode: '048',
      names: {
        'zh': '巴林',
        'en': 'Bahrain',
        'ms': 'Bahrain',
        'vi': 'Bahrain',
        'ru': 'Бахрейн',
      },
      languageCodes: ['ar', 'ml'],
    ),
    CountryConfig(
      code: 'BI',
      alpha3: 'BDI',
      numericCode: '108',
      names: {
        'zh': '布隆迪',
        'en': 'Burundi',
        'ms': 'Burundi',
        'vi': 'Burundi',
        'ru': 'Бурунди',
      },
      languageCodes: ['rn', 'fr', 'en', 'sw'],
    ),
    CountryConfig(
      code: 'BJ',
      alpha3: 'BEN',
      numericCode: '204',
      names: {
        'zh': '贝宁',
        'en': 'Benin',
        'ms': 'Benin',
        'vi': 'Benin',
        'ru': 'Бенин',
      },
      languageCodes: ['fr', 'yo'],
    ),
    CountryConfig(
      code: 'BL',
      alpha3: 'BLM',
      numericCode: '652',
      names: {
        'zh': '圣巴泰勒米',
        'en': 'St. Barthélemy',
        'ms': 'St. Barthelemy',
        'vi': 'St. Barthélemy',
        'ru': 'Сен-Бартелеми',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'BM',
      alpha3: 'BMU',
      numericCode: '060',
      names: {
        'zh': '百慕大',
        'en': 'Bermuda',
        'ms': 'Bermuda',
        'vi': 'Bermuda',
        'ru': 'Бермудские о-ва',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'BN',
      alpha3: 'BRN',
      numericCode: '096',
      names: {
        'zh': '文莱',
        'en': 'Brunei',
        'ms': 'Brunei',
        'vi': 'Brunei',
        'ru': 'Бруней',
      },
      languageCodes: ['ms', 'zh', 'en'],
    ),
    CountryConfig(
      code: 'BO',
      alpha3: 'BOL',
      numericCode: '068',
      names: {
        'zh': '玻利维亚',
        'en': 'Bolivia',
        'ms': 'Bolivia',
        'vi': 'Bolivia',
        'ru': 'Боливия',
      },
      languageCodes: ['es', 'qu', 'gn'],
    ),
    CountryConfig(
      code: 'BQ',
      alpha3: 'BES',
      numericCode: '535',
      names: {
        'zh': '荷属加勒比区',
        'en': 'Caribbean Netherlands',
        'ms': 'Belanda Caribbean',
        'vi': 'Ca-ri-bê Hà Lan',
        'ru': 'Бонэйр, Синт-Эстатиус и Саба',
      },
      languageCodes: ['nl'],
    ),
    CountryConfig(
      code: 'BR',
      alpha3: 'BRA',
      numericCode: '076',
      names: {
        'zh': '巴西',
        'en': 'Brazil',
        'ms': 'Brazil',
        'vi': 'Brazil',
        'ru': 'Бразилия',
      },
      languageCodes: ['pt', 'en', 'de', 'it', 'ja', 'es', 'ko'],
    ),
    CountryConfig(
      code: 'BS',
      alpha3: 'BHS',
      numericCode: '044',
      names: {
        'zh': '巴哈马',
        'en': 'Bahamas',
        'ms': 'Bahamas',
        'vi': 'Bahamas',
        'ru': 'Багамы',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'BT',
      alpha3: 'BTN',
      numericCode: '064',
      names: {
        'zh': '不丹',
        'en': 'Bhutan',
        'ms': 'Bhutan',
        'vi': 'Bhutan',
        'ru': 'Бутан',
      },
      languageCodes: ['ne', 'en'],
    ),
    CountryConfig(
      code: 'BV',
      alpha3: 'BVT',
      numericCode: '074',
      names: {
        'zh': '布韦岛',
        'en': 'Bouvet Island',
        'ms': 'Pulau Bouvet',
        'vi': 'Đảo Bouvet',
        'ru': 'о-в Буве',
      },
      languageCodes: ['no'],
    ),
    CountryConfig(
      code: 'BW',
      alpha3: 'BWA',
      numericCode: '072',
      names: {
        'zh': '博茨瓦纳',
        'en': 'Botswana',
        'ms': 'Botswana',
        'vi': 'Botswana',
        'ru': 'Ботсвана',
      },
      languageCodes: ['en', 'tn', 'af'],
    ),
    CountryConfig(
      code: 'BY',
      alpha3: 'BLR',
      numericCode: '112',
      names: {
        'zh': '白俄罗斯',
        'en': 'Belarus',
        'ms': 'Belarus',
        'vi': 'Belarus',
        'ru': 'Беларусь',
      },
      languageCodes: ['ru'],
    ),
    CountryConfig(
      code: 'BZ',
      alpha3: 'BLZ',
      numericCode: '084',
      names: {
        'zh': '伯利兹',
        'en': 'Belize',
        'ms': 'Belize',
        'vi': 'Belize',
        'ru': 'Белиз',
      },
      languageCodes: ['en', 'es'],
    ),
    CountryConfig(
      code: 'CA',
      alpha3: 'CAN',
      numericCode: '124',
      names: {
        'zh': '加拿大',
        'en': 'Canada',
        'ms': 'Kanada',
        'vi': 'Canada',
        'ru': 'Канада',
      },
      languageCodes: [
        'en',
        'fr',
        'iu',
        'es',
        'zh',
        'pa',
        'ar',
        'hi',
        'tl',
        'it',
        'de',
        'ur',
        'pt',
        'ru',
        'ta',
        'vi',
        'fa',
        'gu',
        'ko',
        'pl',
        'el',
        'uk',
        'bn',
        'ro',
        'nl',
        'ja',
        'sr',
        'tr',
        'hr',
        'hu',
        'so',
      ],
    ),
    CountryConfig(
      code: 'CC',
      alpha3: 'CCK',
      numericCode: '166',
      names: {
        'zh': '科科斯（基林）群岛',
        'en': 'Cocos (Keeling) Islands',
        'ms': 'Kepulauan Cocos (Keeling)',
        'vi': 'Quần đảo Cocos (Keeling)',
        'ru': 'Кокосовые о-ва',
      },
      languageCodes: ['en', 'ms'],
    ),
    CountryConfig(
      code: 'CD',
      alpha3: 'COD',
      numericCode: '180',
      names: {
        'zh': '刚果（金）',
        'en': 'Congo - Kinshasa',
        'ms': 'Congo - Kinshasa',
        'vi': 'Congo - Kinshasa',
        'ru': 'Конго - Киншаса',
      },
      languageCodes: ['fr', 'sw', 'ln', 'rw'],
    ),
    CountryConfig(
      code: 'CF',
      alpha3: 'CAF',
      numericCode: '140',
      names: {
        'zh': '中非共和国',
        'en': 'Central African Republic',
        'ms': 'Republik Afrika Tengah',
        'vi': 'Cộng hòa Trung Phi',
        'ru': 'Центрально-Африканская Республика',
      },
      languageCodes: ['fr', 'ln'],
    ),
    CountryConfig(
      code: 'CG',
      alpha3: 'COG',
      numericCode: '178',
      names: {
        'zh': '刚果（布）',
        'en': 'Congo - Brazzaville',
        'ms': 'Congo - Brazzaville',
        'vi': 'Congo - Brazzaville',
        'ru': 'Конго - Браззавиль',
      },
      languageCodes: ['fr', 'ln'],
    ),
    CountryConfig(
      code: 'CH',
      alpha3: 'CHE',
      numericCode: '756',
      names: {
        'zh': '瑞士',
        'en': 'Switzerland',
        'ms': 'Switzerland',
        'vi': 'Thụy Sĩ',
        'ru': 'Швейцария',
      },
      languageCodes: ['de', 'fr', 'it', 'en', 'pt'],
    ),
    CountryConfig(
      code: 'CI',
      alpha3: 'CIV',
      numericCode: '384',
      names: {
        'zh': '科特迪瓦',
        'en': 'Côte d’Ivoire',
        'ms': 'Cote d’Ivoire',
        'vi': 'Côte d’Ivoire',
        'ru': 'Кот-д’Ивуар',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'CK',
      alpha3: 'COK',
      numericCode: '184',
      names: {
        'zh': '库克群岛',
        'en': 'Cook Islands',
        'ms': 'Kepulauan Cook',
        'vi': 'Quần đảo Cook',
        'ru': 'о-ва Кука',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'CL',
      alpha3: 'CHL',
      numericCode: '152',
      names: {
        'zh': '智利',
        'en': 'Chile',
        'ms': 'Chile',
        'vi': 'Chile',
        'ru': 'Чили',
      },
      languageCodes: ['es', 'en'],
    ),
    CountryConfig(
      code: 'CM',
      alpha3: 'CMR',
      numericCode: '120',
      names: {
        'zh': '喀麦隆',
        'en': 'Cameroon',
        'ms': 'Cameroon',
        'vi': 'Cameroon',
        'ru': 'Камерун',
      },
      languageCodes: ['fr', 'en', 'ar', 'ha'],
    ),
    CountryConfig(
  code: 'CN',
  alpha3: 'CHN',
  numericCode: '156',
  names: {
    'zh': '中国',
    'en': 'China',
    'ms': 'China',
    'vi': 'Trung Quốc',
    'ru': 'Китай',
  },
  languageCodes: [
    'zh',
    'ug',
    'mn',
    'bo',
    'ko',
    'kk',
    'ky',
  ],
  languageRelations: [
    CountryLanguageConfig(
      languageCode: 'zh',
      variantCodes: [
        'cmn',
        'yue',
        'hak',
        'nan',
        'wuu',
      ],
      defaultVariantCode: 'cmn',
      allowDirectSelection: true,
    ),
  ],
),
    CountryConfig(
      code: 'CO',
      alpha3: 'COL',
      numericCode: '170',
      names: {
        'zh': '哥伦比亚',
        'en': 'Colombia',
        'ms': 'Colombia',
        'vi': 'Colombia',
        'ru': 'Колумбия',
      },
      languageCodes: ['es'],
    ),
    CountryConfig(
      code: 'CR',
      alpha3: 'CRI',
      numericCode: '188',
      names: {
        'zh': '哥斯达黎加',
        'en': 'Costa Rica',
        'ms': 'Costa Rica',
        'vi': 'Costa Rica',
        'ru': 'Коста-Рика',
      },
      languageCodes: ['es'],
    ),
    CountryConfig(
      code: 'CU',
      alpha3: 'CUB',
      numericCode: '192',
      names: {
        'zh': '古巴',
        'en': 'Cuba',
        'ms': 'Cuba',
        'vi': 'Cuba',
        'ru': 'Куба',
      },
      languageCodes: ['es'],
    ),
    CountryConfig(
      code: 'CV',
      alpha3: 'CPV',
      numericCode: '132',
      names: {
        'zh': '佛得角',
        'en': 'Cape Verde',
        'ms': 'Cape Verde',
        'vi': 'Cape Verde',
        'ru': 'Кабо-Верде',
      },
      languageCodes: ['pt'],
    ),
    CountryConfig(
      code: 'CW',
      alpha3: 'CUW',
      numericCode: '531',
      names: {
        'zh': '库拉索',
        'en': 'Curaçao',
        'ms': 'Curacao',
        'vi': 'Curaçao',
        'ru': 'Кюрасао',
      },
      languageCodes: ['nl', 'es'],
    ),
    CountryConfig(
      code: 'CX',
      alpha3: 'CXR',
      numericCode: '162',
      names: {
        'zh': '圣诞岛',
        'en': 'Christmas Island',
        'ms': 'Pulau Krismas',
        'vi': 'Đảo Giáng Sinh',
        'ru': 'о-в Рождества',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'CY',
      alpha3: 'CYP',
      numericCode: '196',
      names: {
        'zh': '塞浦路斯',
        'en': 'Cyprus',
        'ms': 'Cyprus',
        'vi': 'Síp',
        'ru': 'Кипр',
      },
      languageCodes: ['el', 'tr', 'en', 'fr', 'hy', 'ar'],
    ),
    CountryConfig(
      code: 'CZ',
      alpha3: 'CZE',
      numericCode: '203',
      names: {
        'zh': '捷克',
        'en': 'Czechia',
        'ms': 'Czechia',
        'vi': 'Séc',
        'ru': 'Чехия',
      },
      languageCodes: ['cs', 'en', 'sk', 'de', 'pl'],
    ),
    CountryConfig(
      code: 'DE',
      alpha3: 'DEU',
      numericCode: '276',
      names: {
        'zh': '德国',
        'en': 'Germany',
        'ms': 'Jerman',
        'vi': 'Đức',
        'ru': 'Германия',
      },
      languageCodes: [
        'de',
        'en',
        'fr',
        'nl',
        'it',
        'es',
        'ru',
        'tr',
        'da',
        'hr',
        'ku',
        'el',
        'pl',
      ],
    ),
    CountryConfig(
      code: 'DJ',
      alpha3: 'DJI',
      numericCode: '262',
      names: {
        'zh': '吉布提',
        'en': 'Djibouti',
        'ms': 'Djibouti',
        'vi': 'Djibouti',
        'ru': 'Джибути',
      },
      languageCodes: ['fr', 'ar', 'so'],
    ),
    CountryConfig(
      code: 'DK',
      alpha3: 'DNK',
      numericCode: '208',
      names: {
        'zh': '丹麦',
        'en': 'Denmark',
        'ms': 'Denmark',
        'vi': 'Đan Mạch',
        'ru': 'Дания',
      },
      languageCodes: ['da', 'de', 'en', 'sv'],
    ),
    CountryConfig(
      code: 'DM',
      alpha3: 'DMA',
      numericCode: '212',
      names: {
        'zh': '多米尼克',
        'en': 'Dominica',
        'ms': 'Dominica',
        'vi': 'Dominica',
        'ru': 'Доминика',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'DO',
      alpha3: 'DOM',
      numericCode: '214',
      names: {
        'zh': '多米尼加共和国',
        'en': 'Dominican Republic',
        'ms': 'Republik Dominica',
        'vi': 'Cộng hòa Dominica',
        'ru': 'Доминиканская Республика',
      },
      languageCodes: ['es', 'en'],
    ),
    CountryConfig(
      code: 'DZ',
      alpha3: 'DZA',
      numericCode: '012',
      names: {
        'zh': '阿尔及利亚',
        'en': 'Algeria',
        'ms': 'Algeria',
        'vi': 'Algeria',
        'ru': 'Алжир',
      },
      languageCodes: ['ar', 'fr', 'en'],
    ),
    CountryConfig(
      code: 'EC',
      alpha3: 'ECU',
      numericCode: '218',
      names: {
        'zh': '厄瓜多尔',
        'en': 'Ecuador',
        'ms': 'Ecuador',
        'vi': 'Ecuador',
        'ru': 'Эквадор',
      },
      languageCodes: ['es', 'qu'],
    ),
    CountryConfig(
      code: 'EE',
      alpha3: 'EST',
      numericCode: '233',
      names: {
        'zh': '爱沙尼亚',
        'en': 'Estonia',
        'ms': 'Estonia',
        'vi': 'Estonia',
        'ru': 'Эстония',
      },
      languageCodes: ['ru', 'en', 'fi'],
    ),
    CountryConfig(
      code: 'EG',
      alpha3: 'EGY',
      numericCode: '818',
      names: {
        'zh': '埃及',
        'en': 'Egypt',
        'ms': 'Mesir',
        'vi': 'Ai Cập',
        'ru': 'Египет',
      },
      languageCodes: ['ar', 'en', 'el'],
    ),
    CountryConfig(
      code: 'EH',
      alpha3: 'ESH',
      numericCode: '732',
      names: {
        'zh': '西撒哈拉',
        'en': 'Western Sahara',
        'ms': 'Sahara Barat',
        'vi': 'Tây Sahara',
        'ru': 'Западная Сахара',
      },
      languageCodes: ['ar'],
    ),
    CountryConfig(
      code: 'ER',
      alpha3: 'ERI',
      numericCode: '232',
      names: {
        'zh': '厄立特里亚',
        'en': 'Eritrea',
        'ms': 'Eritrea',
        'vi': 'Eritrea',
        'ru': 'Эритрея',
      },
      languageCodes: ['en', 'ar'],
    ),
    CountryConfig(
      code: 'ES',
      alpha3: 'ESP',
      numericCode: '724',
      names: {
        'zh': '西班牙',
        'en': 'Spain',
        'ms': 'Sepanyol',
        'vi': 'Tây Ban Nha',
        'ru': 'Испания',
      },
      languageCodes: ['es', 'ca', 'gl', 'en'],
    ),
    CountryConfig(
      code: 'ET',
      alpha3: 'ETH',
      numericCode: '231',
      names: {
        'zh': '埃塞俄比亚',
        'en': 'Ethiopia',
        'ms': 'Ethiopia',
        'vi': 'Ethiopia',
        'ru': 'Эфиопия',
      },
      languageCodes: ['en', 'so'],
    ),
    CountryConfig(
      code: 'FI',
      alpha3: 'FIN',
      numericCode: '246',
      names: {
        'zh': '芬兰',
        'en': 'Finland',
        'ms': 'Finland',
        'vi': 'Phần Lan',
        'ru': 'Финляндия',
      },
      languageCodes: ['fi', 'sv', 'en', 'de', 'ru'],
    ),
    CountryConfig(
      code: 'FJ',
      alpha3: 'FJI',
      numericCode: '242',
      names: {
        'zh': '斐济',
        'en': 'Fiji',
        'ms': 'Fiji',
        'vi': 'Fiji',
        'ru': 'Фиджи',
      },
      languageCodes: ['en', 'fj', 'hi'],
    ),
    CountryConfig(
      code: 'FK',
      alpha3: 'FLK',
      numericCode: '238',
      names: {
        'zh': '福克兰群岛',
        'en': 'Falkland Islands',
        'ms': 'Kepulauan Falkland',
        'vi': 'Quần đảo Falkland',
        'ru': 'Фолклендские о-ва',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'FM',
      alpha3: 'FSM',
      numericCode: '583',
      names: {
        'zh': '密克罗尼西亚',
        'en': 'Micronesia',
        'ms': 'Micronesia',
        'vi': 'Micronesia',
        'ru': 'Федеративные Штаты Микронезии',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'FO',
      alpha3: 'FRO',
      numericCode: '234',
      names: {
        'zh': '法罗群岛',
        'en': 'Faroe Islands',
        'ms': 'Kepulauan Faroe',
        'vi': 'Quần đảo Faroe',
        'ru': 'Фарерские о-ва',
      },
    ),
    CountryConfig(
      code: 'FR',
      alpha3: 'FRA',
      numericCode: '250',
      names: {
        'zh': '法国',
        'en': 'France',
        'ms': 'Perancis',
        'vi': 'Pháp',
        'ru': 'Франция',
      },
      languageCodes: ['fr', 'en', 'es', 'de', 'it', 'pt', 'ca', 'nl'],
    ),
    CountryConfig(
      code: 'GA',
      alpha3: 'GAB',
      numericCode: '266',
      names: {
        'zh': '加蓬',
        'en': 'Gabon',
        'ms': 'Gabon',
        'vi': 'Gabon',
        'ru': 'Габон',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'GB',
      alpha3: 'GBR',
      numericCode: '826',
      names: {
        'zh': '英国',
        'en': 'United Kingdom',
        'ms': 'United Kingdom',
        'vi': 'Vương quốc Anh',
        'ru': 'Великобритания',
      },
      languageCodes: [
        'en',
        'cy',
        'fr',
        'de',
        'es',
        'pl',
        'pa',
        'ur',
        'ta',
        'gu',
        'ro',
        'bn',
        'ar',
        'zh',
        'it',
        'lt',
        'pt',
        'so',
        'tr',
      ],
    ),
    CountryConfig(
      code: 'GD',
      alpha3: 'GRD',
      numericCode: '308',
      names: {
        'zh': '格林纳达',
        'en': 'Grenada',
        'ms': 'Grenada',
        'vi': 'Grenada',
        'ru': 'Гренада',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'GE',
      alpha3: 'GEO',
      numericCode: '268',
      names: {
        'zh': '格鲁吉亚',
        'en': 'Georgia',
        'ms': 'Georgia',
        'vi': 'Georgia',
        'ru': 'Грузия',
      },
      languageCodes: ['ka', 'ru', 'hy', 'ku'],
    ),
    CountryConfig(
      code: 'GF',
      alpha3: 'GUF',
      numericCode: '254',
      names: {
        'zh': '法属圭亚那',
        'en': 'French Guiana',
        'ms': 'Guiana Perancis',
        'vi': 'Guiana thuộc Pháp',
        'ru': 'Французская Гвиана',
      },
      languageCodes: ['fr', 'zh'],
    ),
    CountryConfig(
      code: 'GG',
      alpha3: 'GGY',
      numericCode: '831',
      names: {
        'zh': '根西岛',
        'en': 'Guernsey',
        'ms': 'Guernsey',
        'vi': 'Guernsey',
        'ru': 'Гернси',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'GH',
      alpha3: 'GHA',
      numericCode: '288',
      names: {
        'zh': '加纳',
        'en': 'Ghana',
        'ms': 'Ghana',
        'vi': 'Ghana',
        'ru': 'Гана',
      },
      languageCodes: ['en', 'ha'],
    ),
    CountryConfig(
      code: 'GI',
      alpha3: 'GIB',
      numericCode: '292',
      names: {
        'zh': '直布罗陀',
        'en': 'Gibraltar',
        'ms': 'Gibraltar',
        'vi': 'Gibraltar',
        'ru': 'Гибралтар',
      },
      languageCodes: ['en', 'es'],
    ),
    CountryConfig(
      code: 'GL',
      alpha3: 'GRL',
      numericCode: '304',
      names: {
        'zh': '格陵兰',
        'en': 'Greenland',
        'ms': 'Greenland',
        'vi': 'Greenland',
        'ru': 'Гренландия',
      },
      languageCodes: ['da'],
    ),
    CountryConfig(
      code: 'GM',
      alpha3: 'GMB',
      numericCode: '270',
      names: {
        'zh': '冈比亚',
        'en': 'Gambia',
        'ms': 'Gambia',
        'vi': 'Gambia',
        'ru': 'Гамбия',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'GN',
      alpha3: 'GIN',
      numericCode: '324',
      names: {
        'zh': '几内亚',
        'en': 'Guinea',
        'ms': 'Guinea',
        'vi': 'Guinea',
        'ru': 'Гвинея',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'GP',
      alpha3: 'GLP',
      numericCode: '312',
      names: {
        'zh': '瓜德罗普',
        'en': 'Guadeloupe',
        'ms': 'Guadeloupe',
        'vi': 'Guadeloupe',
        'ru': 'Гваделупа',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'GQ',
      alpha3: 'GNQ',
      numericCode: '226',
      names: {
        'zh': '赤道几内亚',
        'en': 'Equatorial Guinea',
        'ms': 'Guinea Khatulistiwa',
        'vi': 'Guinea Xích Đạo',
        'ru': 'Экваториальная Гвинея',
      },
      languageCodes: ['es', 'fr', 'pt'],
    ),
    CountryConfig(
      code: 'GR',
      alpha3: 'GRC',
      numericCode: '300',
      names: {
        'zh': '希腊',
        'en': 'Greece',
        'ms': 'Greece',
        'vi': 'Hy Lạp',
        'ru': 'Греция',
      },
      languageCodes: ['el', 'en', 'fr', 'de', 'mk', 'tr'],
    ),
    CountryConfig(
      code: 'GS',
      alpha3: 'SGS',
      numericCode: '239',
      names: {
        'zh': '南乔治亚和南桑威奇群岛',
        'en': 'South Georgia & South Sandwich Islands',
        'ms': 'Kepulauan Georgia Selatan & Sandwich Selatan',
        'vi': 'Nam Georgia & Quần đảo Nam Sandwich',
        'ru': 'Южная Георгия и Южные Сандвичевы о-ва',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'GT',
      alpha3: 'GTM',
      numericCode: '320',
      names: {
        'zh': '危地马拉',
        'en': 'Guatemala',
        'ms': 'Guatemala',
        'vi': 'Guatemala',
        'ru': 'Гватемала',
      },
      languageCodes: ['es'],
    ),
    CountryConfig(
      code: 'GU',
      alpha3: 'GUM',
      numericCode: '316',
      names: {
        'zh': '关岛',
        'en': 'Guam',
        'ms': 'Guam',
        'vi': 'Guam',
        'ru': 'Гуам',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'GW',
      alpha3: 'GNB',
      numericCode: '624',
      names: {
        'zh': '几内亚比绍',
        'en': 'Guinea-Bissau',
        'ms': 'Guinea Bissau',
        'vi': 'Guinea-Bissau',
        'ru': 'Гвинея-Бисау',
      },
      languageCodes: ['pt', 'fr'],
    ),
    CountryConfig(
      code: 'GY',
      alpha3: 'GUY',
      numericCode: '328',
      names: {
        'zh': '圭亚那',
        'en': 'Guyana',
        'ms': 'Guyana',
        'vi': 'Guyana',
        'ru': 'Гайана',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'HK',
      alpha3: 'HKG',
      numericCode: '344',
      names: {
        'zh': '中国香港特别行政区',
        'en': 'Hong Kong SAR China',
        'ms': 'Hong Kong SAR China',
        'vi': 'Đặc khu Hành chính Hồng Kông, Trung Quốc',
        'ru': 'Гонконг (САР)',
      },
      languageCodes: ['zh', 'en'],
            languageRelations: [
        CountryLanguageConfig(
          languageCode: 'zh',
          variantCodes: [
            'yue',
            'cmn',
          ],
          defaultVariantCode: 'yue',
          allowDirectSelection: true,
        ),
      ],
    ),
    CountryConfig(
      code: 'HM',
      alpha3: 'HMD',
      numericCode: '334',
      names: {
        'zh': '赫德岛和麦克唐纳群岛',
        'en': 'Heard & McDonald Islands',
        'ms': 'Kepulauan Heard & McDonald',
        'vi': 'Quần đảo Heard và McDonald',
        'ru': 'о-ва Херд и Макдональд',
      },
    ),
    CountryConfig(
      code: 'HN',
      alpha3: 'HND',
      numericCode: '340',
      names: {
        'zh': '洪都拉斯',
        'en': 'Honduras',
        'ms': 'Honduras',
        'vi': 'Honduras',
        'ru': 'Гондурас',
      },
      languageCodes: ['es', 'en'],
    ),
    CountryConfig(
      code: 'HR',
      alpha3: 'HRV',
      numericCode: '191',
      names: {
        'zh': '克罗地亚',
        'en': 'Croatia',
        'ms': 'Croatia',
        'vi': 'Croatia',
        'ru': 'Хорватия',
      },
      languageCodes: ['hr', 'it', 'en'],
    ),
    CountryConfig(
      code: 'HT',
      alpha3: 'HTI',
      numericCode: '332',
      names: {
        'zh': '海地',
        'en': 'Haiti',
        'ms': 'Haiti',
        'vi': 'Haiti',
        'ru': 'Гаити',
      },
      languageCodes: ['ht', 'fr'],
    ),
    CountryConfig(
      code: 'HU',
      alpha3: 'HUN',
      numericCode: '348',
      names: {
        'zh': '匈牙利',
        'en': 'Hungary',
        'ms': 'Hungary',
        'vi': 'Hungary',
        'ru': 'Венгрия',
      },
      languageCodes: ['hu', 'en', 'de', 'fr', 'ro', 'hr', 'sk', 'sl'],
    ),
    CountryConfig(
      code: 'ID',
      alpha3: 'IDN',
      numericCode: '360',
      names: {
        'zh': '印度尼西亚',
        'en': 'Indonesia',
        'ms': 'Indonesia',
        'vi': 'Indonesia',
        'ru': 'Индонезия',
      },
      languageCodes: ['id', 'jv', 'su', 'ms', 'zh'],
    ),
    CountryConfig(
      code: 'IE',
      alpha3: 'IRL',
      numericCode: '372',
      names: {
        'zh': '爱尔兰',
        'en': 'Ireland',
        'ms': 'Ireland',
        'vi': 'Ireland',
        'ru': 'Ирландия',
      },
      languageCodes: ['en', 'fr'],
    ),
    CountryConfig(
      code: 'IL',
      alpha3: 'ISR',
      numericCode: '376',
      names: {
        'zh': '以色列',
        'en': 'Israel',
        'ms': 'Israel',
        'vi': 'Israel',
        'ru': 'Израиль',
      },
      languageCodes: ['he', 'ar', 'en', 'ru', 'ro', 'yi', 'pl', 'hu', 'ml'],
    ),
    CountryConfig(
      code: 'IM',
      alpha3: 'IMN',
      numericCode: '833',
      names: {
        'zh': '马恩岛',
        'en': 'Isle of Man',
        'ms': 'Isle of Man',
        'vi': 'Đảo Man',
        'ru': 'о-в Мэн',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'IN',
      alpha3: 'IND',
      numericCode: '356',
      names: {
        'zh': '印度',
        'en': 'India',
        'ms': 'India',
        'vi': 'Ấn Độ',
        'ru': 'Индия',
      },
      languageCodes: [
        'hi',
        'en',
        'bn',
        'te',
        'mr',
        'ta',
        'ur',
        'gu',
        'kn',
        'ml',
        'pa',
        'ne',
        'sd',
        'sa',
        'bo',
      ],
    ),
    CountryConfig(
      code: 'IO',
      alpha3: 'IOT',
      numericCode: '086',
      names: {
        'zh': '英属印度洋领地',
        'en': 'British Indian Ocean Territory',
        'ms': 'Wilayah Lautan Hindi British',
        'vi': 'Lãnh thổ Ấn Độ Dương thuộc Anh',
        'ru': 'Британская территория в Индийском океане',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'IQ',
      alpha3: 'IRQ',
      numericCode: '368',
      names: {
        'zh': '伊拉克',
        'en': 'Iraq',
        'ms': 'Iraq',
        'vi': 'Iraq',
        'ru': 'Ирак',
      },
      languageCodes: ['ar', 'en', 'fa'],
    ),
    CountryConfig(
      code: 'IR',
      alpha3: 'IRN',
      numericCode: '364',
      names: {
        'zh': '伊朗',
        'en': 'Iran',
        'ms': 'Iran',
        'vi': 'Iran',
        'ru': 'Иран',
      },
      languageCodes: ['fa', 'tk', 'ar', 'hy', 'ps', 'ka'],
    ),
    CountryConfig(
      code: 'IS',
      alpha3: 'ISL',
      numericCode: '352',
      names: {
        'zh': '冰岛',
        'en': 'Iceland',
        'ms': 'Iceland',
        'vi': 'Iceland',
        'ru': 'Исландия',
      },
      languageCodes: ['is', 'da'],
    ),
    CountryConfig(
      code: 'IT',
      alpha3: 'ITA',
      numericCode: '380',
      names: {
        'zh': '意大利',
        'en': 'Italy',
        'ms': 'Itali',
        'vi': 'Italy',
        'ru': 'Италия',
      },
      languageCodes: ['it', 'fr', 'en', 'de', 'sl', 'ca', 'el', 'hr'],
    ),
    CountryConfig(
      code: 'JE',
      alpha3: 'JEY',
      numericCode: '832',
      names: {
        'zh': '泽西岛',
        'en': 'Jersey',
        'ms': 'Jersey',
        'vi': 'Jersey',
        'ru': 'Джерси',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'JM',
      alpha3: 'JAM',
      numericCode: '388',
      names: {
        'zh': '牙买加',
        'en': 'Jamaica',
        'ms': 'Jamaica',
        'vi': 'Jamaica',
        'ru': 'Ямайка',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'JO',
      alpha3: 'JOR',
      numericCode: '400',
      names: {
        'zh': '约旦',
        'en': 'Jordan',
        'ms': 'Jordan',
        'vi': 'Jordan',
        'ru': 'Иордания',
      },
      languageCodes: ['ar', 'en'],
    ),
    CountryConfig(
      code: 'JP',
      alpha3: 'JPN',
      numericCode: '392',
      names: {
        'zh': '日本',
        'en': 'Japan',
        'ms': 'Jepun',
        'vi': 'Nhật Bản',
        'ru': 'Япония',
      },
      languageCodes: ['ja', 'ko'],
    ),
    CountryConfig(
      code: 'KE',
      alpha3: 'KEN',
      numericCode: '404',
      names: {
        'zh': '肯尼亚',
        'en': 'Kenya',
        'ms': 'Kenya',
        'vi': 'Kenya',
        'ru': 'Кения',
      },
      languageCodes: ['sw', 'en', 'so', 'ar', 'pa', 'gu'],
    ),
    CountryConfig(
      code: 'KG',
      alpha3: 'KGZ',
      numericCode: '417',
      names: {
        'zh': '吉尔吉斯斯坦',
        'en': 'Kyrgyzstan',
        'ms': 'Kyrgyzstan',
        'vi': 'Kyrgyzstan',
        'ru': 'Киргизия',
      },
      languageCodes: ['ky', 'ru'],
    ),
    CountryConfig(
      code: 'KH',
      alpha3: 'KHM',
      numericCode: '116',
      names: {
        'zh': '柬埔寨',
        'en': 'Cambodia',
        'ms': 'Kemboja',
        'vi': 'Campuchia',
        'ru': 'Камбоджа',
      },
      languageCodes: ['km'],
    ),
    CountryConfig(
      code: 'KI',
      alpha3: 'KIR',
      numericCode: '296',
      names: {
        'zh': '基里巴斯',
        'en': 'Kiribati',
        'ms': 'Kiribati',
        'vi': 'Kiribati',
        'ru': 'Кирибати',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'KM',
      alpha3: 'COM',
      numericCode: '174',
      names: {
        'zh': '科摩罗',
        'en': 'Comoros',
        'ms': 'Comoros',
        'vi': 'Comoros',
        'ru': 'Коморы',
      },
      languageCodes: ['ar', 'fr'],
    ),
    CountryConfig(
      code: 'KN',
      alpha3: 'KNA',
      numericCode: '659',
      names: {
        'zh': '圣基茨和尼维斯',
        'en': 'St. Kitts & Nevis',
        'ms': 'Saint Kitts dan Nevis',
        'vi': 'St. Kitts và Nevis',
        'ru': 'Сент-Китс и Невис',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'KP',
      alpha3: 'PRK',
      numericCode: '408',
      names: {
        'zh': '朝鲜',
        'en': 'North Korea',
        'ms': 'Korea Utara',
        'vi': 'Triều Tiên',
        'ru': 'КНДР',
      },
      languageCodes: ['ko'],
    ),
    CountryConfig(
      code: 'KR',
      alpha3: 'KOR',
      numericCode: '410',
      names: {
        'zh': '韩国',
        'en': 'South Korea',
        'ms': 'Korea Selatan',
        'vi': 'Hàn Quốc',
        'ru': 'Республика Корея',
      },
      languageCodes: ['ko'],
    ),
    CountryConfig(
      code: 'KW',
      alpha3: 'KWT',
      numericCode: '414',
      names: {
        'zh': '科威特',
        'en': 'Kuwait',
        'ms': 'Kuwait',
        'vi': 'Kuwait',
        'ru': 'Кувейт',
      },
      languageCodes: ['ar'],
    ),
    CountryConfig(
      code: 'KY',
      alpha3: 'CYM',
      numericCode: '136',
      names: {
        'zh': '开曼群岛',
        'en': 'Cayman Islands',
        'ms': 'Kepulauan Cayman',
        'vi': 'Quần đảo Cayman',
        'ru': 'о-ва Кайман',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'KZ',
      alpha3: 'KAZ',
      numericCode: '398',
      names: {
        'zh': '哈萨克斯坦',
        'en': 'Kazakhstan',
        'ms': 'Kazakhstan',
        'vi': 'Kazakhstan',
        'ru': 'Казахстан',
      },
      languageCodes: ['ru', 'kk', 'en', 'de', 'ug'],
    ),
    CountryConfig(
      code: 'LA',
      alpha3: 'LAO',
      numericCode: '418',
      names: {
        'zh': '老挝',
        'en': 'Laos',
        'ms': 'Laos',
        'vi': 'Lào',
        'ru': 'Лаос',
      },
      languageCodes: ['lo'],
    ),
    CountryConfig(
      code: 'LB',
      alpha3: 'LBN',
      numericCode: '422',
      names: {
        'zh': '黎巴嫩',
        'en': 'Lebanon',
        'ms': 'Lubnan',
        'vi': 'Li-băng',
        'ru': 'Ливан',
      },
      languageCodes: ['ar', 'en', 'fr', 'hy', 'ku'],
    ),
    CountryConfig(
      code: 'LC',
      alpha3: 'LCA',
      numericCode: '662',
      names: {
        'zh': '圣卢西亚',
        'en': 'St. Lucia',
        'ms': 'Saint Lucia',
        'vi': 'St. Lucia',
        'ru': 'Сент-Люсия',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'LI',
      alpha3: 'LIE',
      numericCode: '438',
      names: {
        'zh': '列支敦士登',
        'en': 'Liechtenstein',
        'ms': 'Liechtenstein',
        'vi': 'Liechtenstein',
        'ru': 'Лихтенштейн',
      },
      languageCodes: ['de'],
    ),
    CountryConfig(
      code: 'LK',
      alpha3: 'LKA',
      numericCode: '144',
      names: {
        'zh': '斯里兰卡',
        'en': 'Sri Lanka',
        'ms': 'Sri Lanka',
        'vi': 'Sri Lanka',
        'ru': 'Шри-Ланка',
      },
      languageCodes: ['si', 'ta', 'en'],
    ),
    CountryConfig(
      code: 'LR',
      alpha3: 'LBR',
      numericCode: '430',
      names: {
        'zh': '利比里亚',
        'en': 'Liberia',
        'ms': 'Liberia',
        'vi': 'Liberia',
        'ru': 'Либерия',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'LS',
      alpha3: 'LSO',
      numericCode: '426',
      names: {
        'zh': '莱索托',
        'en': 'Lesotho',
        'ms': 'Lesotho',
        'vi': 'Lesotho',
        'ru': 'Лесото',
      },
      languageCodes: ['st', 'en'],
    ),
    CountryConfig(
      code: 'LT',
      alpha3: 'LTU',
      numericCode: '440',
      names: {
        'zh': '立陶宛',
        'en': 'Lithuania',
        'ms': 'Lithuania',
        'vi': 'Litva',
        'ru': 'Литва',
      },
      languageCodes: ['lt', 'ru', 'en', 'de'],
    ),
    CountryConfig(
      code: 'LU',
      alpha3: 'LUX',
      numericCode: '442',
      names: {
        'zh': '卢森堡',
        'en': 'Luxembourg',
        'ms': 'Luxembourg',
        'vi': 'Luxembourg',
        'ru': 'Люксембург',
      },
      languageCodes: ['fr', 'lb', 'de', 'en', 'pt'],
    ),
    CountryConfig(
      code: 'LV',
      alpha3: 'LVA',
      numericCode: '428',
      names: {
        'zh': '拉脱维亚',
        'en': 'Latvia',
        'ms': 'Latvia',
        'vi': 'Latvia',
        'ru': 'Латвия',
      },
      languageCodes: ['lv', 'en', 'ru'],
    ),
    CountryConfig(
      code: 'LY',
      alpha3: 'LBY',
      numericCode: '434',
      names: {
        'zh': '利比亚',
        'en': 'Libya',
        'ms': 'Libya',
        'vi': 'Libya',
        'ru': 'Ливия',
      },
      languageCodes: ['ar'],
    ),
    CountryConfig(
      code: 'MA',
      alpha3: 'MAR',
      numericCode: '504',
      names: {
        'zh': '摩洛哥',
        'en': 'Morocco',
        'ms': 'Maghribi',
        'vi': 'Ma-rốc',
        'ru': 'Марокко',
      },
      languageCodes: ['ar', 'fr', 'en', 'es'],
    ),
    CountryConfig(
      code: 'MC',
      alpha3: 'MCO',
      numericCode: '492',
      names: {
        'zh': '摩纳哥',
        'en': 'Monaco',
        'ms': 'Monaco',
        'vi': 'Monaco',
        'ru': 'Монако',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'MD',
      alpha3: 'MDA',
      numericCode: '498',
      names: {
        'zh': '摩尔多瓦',
        'en': 'Moldova',
        'ms': 'Moldova',
        'vi': 'Moldova',
        'ru': 'Молдова',
      },
      languageCodes: ['ro', 'uk', 'ru'],
    ),
    CountryConfig(
      code: 'ME',
      alpha3: 'MNE',
      numericCode: '499',
      names: {
        'zh': '黑山',
        'en': 'Montenegro',
        'ms': 'Montenegro',
        'vi': 'Montenegro',
        'ru': 'Черногория',
      },
      languageCodes: ['sr'],
    ),
    CountryConfig(
      code: 'MF',
      alpha3: 'MAF',
      numericCode: '663',
      names: {
        'zh': '法属圣马丁',
        'en': 'St. Martin',
        'ms': 'Saint Martin',
        'vi': 'St. Martin',
        'ru': 'Сен-Мартен',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'MG',
      alpha3: 'MDG',
      numericCode: '450',
      names: {
        'zh': '马达加斯加',
        'en': 'Madagascar',
        'ms': 'Madagaskar',
        'vi': 'Madagascar',
        'ru': 'Мадагаскар',
      },
      languageCodes: ['mg', 'fr', 'en'],
    ),
    CountryConfig(
      code: 'MH',
      alpha3: 'MHL',
      numericCode: '584',
      names: {
        'zh': '马绍尔群岛',
        'en': 'Marshall Islands',
        'ms': 'Kepulauan Marshall',
        'vi': 'Quần đảo Marshall',
        'ru': 'Маршалловы о-ва',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'MK',
      alpha3: 'MKD',
      numericCode: '807',
      names: {
        'zh': '北马其顿',
        'en': 'North Macedonia',
        'ms': 'Macedonia Utara',
        'vi': 'Bắc Macedonia',
        'ru': 'Северная Македония',
      },
      languageCodes: ['mk', 'tr'],
    ),
    CountryConfig(
      code: 'ML',
      alpha3: 'MLI',
      numericCode: '466',
      names: {
        'zh': '马里',
        'en': 'Mali',
        'ms': 'Mali',
        'vi': 'Mali',
        'ru': 'Мали',
      },
      languageCodes: ['fr', 'ar'],
    ),
    CountryConfig(
      code: 'MM',
      alpha3: 'MMR',
      numericCode: '104',
      names: {
        'zh': '缅甸',
        'en': 'Myanmar (Burma)',
        'ms': 'Myanmar (Burma)',
        'vi': 'Myanmar (Miến Điện)',
        'ru': 'Мьянма (Бирма)',
      },
      languageCodes: ['my'],
    ),
    CountryConfig(
      code: 'MN',
      alpha3: 'MNG',
      numericCode: '496',
      names: {
        'zh': '蒙古',
        'en': 'Mongolia',
        'ms': 'Mongolia',
        'vi': 'Mông Cổ',
        'ru': 'Монголия',
      },
      languageCodes: ['mn', 'kk', 'zh', 'ru', 'ug'],
    ),
    CountryConfig(
      code: 'MO',
      alpha3: 'MAC',
      numericCode: '446',
      names: {
        'zh': '中国澳门特别行政区',
        'en': 'Macao SAR China',
        'ms': 'Macau SAR China',
        'vi': 'Đặc khu Hành chính Macao, Trung Quốc',
        'ru': 'Макао (САР)',
      },
      languageCodes: ['zh', 'pt', 'en', 'tl'],
    ),
    CountryConfig(
      code: 'MP',
      alpha3: 'MNP',
      numericCode: '580',
      names: {
        'zh': '北马里亚纳群岛',
        'en': 'Northern Mariana Islands',
        'ms': 'Kepulauan Mariana Utara',
        'vi': 'Quần đảo Bắc Mariana',
        'ru': 'Северные Марианские о-ва',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'MQ',
      alpha3: 'MTQ',
      numericCode: '474',
      names: {
        'zh': '马提尼克',
        'en': 'Martinique',
        'ms': 'Martinique',
        'vi': 'Martinique',
        'ru': 'Мартиника',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'MR',
      alpha3: 'MRT',
      numericCode: '478',
      names: {
        'zh': '毛里塔尼亚',
        'en': 'Mauritania',
        'ms': 'Mauritania',
        'vi': 'Mauritania',
        'ru': 'Мавритания',
      },
      languageCodes: ['ar', 'fr', 'wo'],
    ),
    CountryConfig(
      code: 'MS',
      alpha3: 'MSR',
      numericCode: '500',
      names: {
        'zh': '蒙特塞拉特',
        'en': 'Montserrat',
        'ms': 'Montserrat',
        'vi': 'Montserrat',
        'ru': 'Монтсеррат',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'MT',
      alpha3: 'MLT',
      numericCode: '470',
      names: {
        'zh': '马耳他',
        'en': 'Malta',
        'ms': 'Malta',
        'vi': 'Malta',
        'ru': 'Мальта',
      },
      languageCodes: ['mt', 'en', 'it', 'fr'],
    ),
    CountryConfig(
      code: 'MU',
      alpha3: 'MUS',
      numericCode: '480',
      names: {
        'zh': '毛里求斯',
        'en': 'Mauritius',
        'ms': 'Mauritius',
        'vi': 'Mauritius',
        'ru': 'Маврикий',
      },
      languageCodes: ['fr', 'en', 'ur', 'ta'],
    ),
    CountryConfig(
      code: 'MV',
      alpha3: 'MDV',
      numericCode: '462',
      names: {
        'zh': '马尔代夫',
        'en': 'Maldives',
        'ms': 'Maldives',
        'vi': 'Maldives',
        'ru': 'Мальдивы',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'MW',
      alpha3: 'MWI',
      numericCode: '454',
      names: {
        'zh': '马拉维',
        'en': 'Malawi',
        'ms': 'Malawi',
        'vi': 'Malawi',
        'ru': 'Малави',
      },
      languageCodes: ['en', 'ny'],
    ),
    CountryConfig(
      code: 'MX',
      alpha3: 'MEX',
      numericCode: '484',
      names: {
        'zh': '墨西哥',
        'en': 'Mexico',
        'ms': 'Mexico',
        'vi': 'Mexico',
        'ru': 'Мексика',
      },
      languageCodes: ['es', 'en'],
    ),
    CountryConfig(
  code: 'MY',
  alpha3: 'MYS',
  numericCode: '458',
  names: {
    'zh': '马来西亚',
    'en': 'Malaysia',
    'ms': 'Malaysia',
    'vi': 'Malaysia',
    'ru': 'Малайзия',
  },
  languageCodes: [
    'ms',
    'en',
    'zh',
    'ta',
    'jv',
    'ml',
  ],
  languageRelations: [
    CountryLanguageConfig(
      languageCode: 'zh',
      variantCodes: [
        'cmn',
        'yue',
        'hak',
        'nan',
      ],
      defaultVariantCode: 'cmn',
      allowDirectSelection: true,
    ),
  ],
),
    CountryConfig(
      code: 'MZ',
      alpha3: 'MOZ',
      numericCode: '508',
      names: {
        'zh': '莫桑比克',
        'en': 'Mozambique',
        'ms': 'Mozambique',
        'vi': 'Mozambique',
        'ru': 'Мозамбик',
      },
      languageCodes: ['pt', 'ny', 'sw'],
    ),
    CountryConfig(
      code: 'NA',
      alpha3: 'NAM',
      numericCode: '516',
      names: {
        'zh': '纳米比亚',
        'en': 'Namibia',
        'ms': 'Namibia',
        'vi': 'Namibia',
        'ru': 'Намибия',
      },
      languageCodes: ['en', 'af', 'de', 'tn'],
    ),
    CountryConfig(
      code: 'NC',
      alpha3: 'NCL',
      numericCode: '540',
      names: {
        'zh': '新喀里多尼亚',
        'en': 'New Caledonia',
        'ms': 'New Caledonia',
        'vi': 'New Caledonia',
        'ru': 'Новая Каледония',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'NE',
      alpha3: 'NER',
      numericCode: '562',
      names: {
        'zh': '尼日尔',
        'en': 'Niger',
        'ms': 'Niger',
        'vi': 'Niger',
        'ru': 'Нигер',
      },
      languageCodes: ['fr', 'ha', 'ar'],
    ),
    CountryConfig(
      code: 'NF',
      alpha3: 'NFK',
      numericCode: '574',
      names: {
        'zh': '诺福克岛',
        'en': 'Norfolk Island',
        'ms': 'Pulau Norfolk',
        'vi': 'Đảo Norfolk',
        'ru': 'о-в Норфолк',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'NG',
      alpha3: 'NGA',
      numericCode: '566',
      names: {
        'zh': '尼日利亚',
        'en': 'Nigeria',
        'ms': 'Nigeria',
        'vi': 'Nigeria',
        'ru': 'Нигерия',
      },
      languageCodes: ['en', 'yo', 'ha', 'ar'],
    ),
    CountryConfig(
      code: 'NI',
      alpha3: 'NIC',
      numericCode: '558',
      names: {
        'zh': '尼加拉瓜',
        'en': 'Nicaragua',
        'ms': 'Nicaragua',
        'vi': 'Nicaragua',
        'ru': 'Никарагуа',
      },
      languageCodes: ['es'],
    ),
    CountryConfig(
      code: 'NL',
      alpha3: 'NLD',
      numericCode: '528',
      names: {
        'zh': '荷兰',
        'en': 'Netherlands',
        'ms': 'Belanda',
        'vi': 'Hà Lan',
        'ru': 'Нидерланды',
      },
      languageCodes: ['nl', 'fy', 'en', 'de', 'fr', 'id', 'tr'],
    ),
    CountryConfig(
      code: 'NO',
      alpha3: 'NOR',
      numericCode: '578',
      names: {
        'zh': '挪威',
        'en': 'Norway',
        'ms': 'Norway',
        'vi': 'Na Uy',
        'ru': 'Норвегия',
      },
      languageCodes: ['no'],
    ),
    CountryConfig(
      code: 'NP',
      alpha3: 'NPL',
      numericCode: '524',
      names: {
        'zh': '尼泊尔',
        'en': 'Nepal',
        'ms': 'Nepal',
        'vi': 'Nepal',
        'ru': 'Непал',
      },
      languageCodes: ['ne', 'en', 'hi', 'bo', 'bn'],
    ),
    CountryConfig(
      code: 'NR',
      alpha3: 'NRU',
      numericCode: '520',
      names: {
        'zh': '瑙鲁',
        'en': 'Nauru',
        'ms': 'Nauru',
        'vi': 'Nauru',
        'ru': 'Науру',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'NU',
      alpha3: 'NIU',
      numericCode: '570',
      names: {
        'zh': '纽埃',
        'en': 'Niue',
        'ms': 'Niue',
        'vi': 'Niue',
        'ru': 'Ниуэ',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'NZ',
      alpha3: 'NZL',
      numericCode: '554',
      names: {
        'zh': '新西兰',
        'en': 'New Zealand',
        'ms': 'New Zealand',
        'vi': 'New Zealand',
        'ru': 'Новая Зеландия',
      },
      languageCodes: ['mi', 'en'],
    ),
    CountryConfig(
      code: 'OM',
      alpha3: 'OMN',
      numericCode: '512',
      names: {
        'zh': '阿曼',
        'en': 'Oman',
        'ms': 'Oman',
        'vi': 'Oman',
        'ru': 'Оман',
      },
      languageCodes: ['ar', 'fa'],
    ),
    CountryConfig(
      code: 'PA',
      alpha3: 'PAN',
      numericCode: '591',
      names: {
        'zh': '巴拿马',
        'en': 'Panama',
        'ms': 'Panama',
        'vi': 'Panama',
        'ru': 'Панама',
      },
      languageCodes: ['es', 'en', 'zh'],
    ),
    CountryConfig(
      code: 'PE',
      alpha3: 'PER',
      numericCode: '604',
      names: {
        'zh': '秘鲁',
        'en': 'Peru',
        'ms': 'Peru',
        'vi': 'Peru',
        'ru': 'Перу',
      },
      languageCodes: ['es', 'qu'],
    ),
    CountryConfig(
      code: 'PF',
      alpha3: 'PYF',
      numericCode: '258',
      names: {
        'zh': '法属波利尼西亚',
        'en': 'French Polynesia',
        'ms': 'Polinesia Perancis',
        'vi': 'Polynesia thuộc Pháp',
        'ru': 'Французская Полинезия',
      },
      languageCodes: ['fr', 'zh'],
    ),
    CountryConfig(
      code: 'PG',
      alpha3: 'PNG',
      numericCode: '598',
      names: {
        'zh': '巴布亚新几内亚',
        'en': 'Papua New Guinea',
        'ms': 'Papua New Guinea',
        'vi': 'Papua New Guinea',
        'ru': 'Папуа — Новая Гвинея',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'PH',
      alpha3: 'PHL',
      numericCode: '608',
      names: {
        'zh': '菲律宾',
        'en': 'Philippines',
        'ms': 'Filipina',
        'vi': 'Philippines',
        'ru': 'Филиппины',
      },
      languageCodes: ['en', 'tl', 'es', 'zh'],
    ),
    CountryConfig(
      code: 'PK',
      alpha3: 'PAK',
      numericCode: '586',
      names: {
        'zh': '巴基斯坦',
        'en': 'Pakistan',
        'ms': 'Pakistan',
        'vi': 'Pakistan',
        'ru': 'Пакистан',
      },
      languageCodes: ['ur', 'en', 'pa', 'ps', 'sd', 'fa', 'tg'],
    ),
    CountryConfig(
      code: 'PL',
      alpha3: 'POL',
      numericCode: '616',
      names: {
        'zh': '波兰',
        'en': 'Poland',
        'ms': 'Poland',
        'vi': 'Ba Lan',
        'ru': 'Польша',
      },
      languageCodes: ['pl', 'de', 'lt', 'en', 'ru', 'uk'],
    ),
    CountryConfig(
      code: 'PM',
      alpha3: 'SPM',
      numericCode: '666',
      names: {
        'zh': '圣皮埃尔和密克隆群岛',
        'en': 'St. Pierre & Miquelon',
        'ms': 'Saint Pierre dan Miquelon',
        'vi': 'Saint Pierre và Miquelon',
        'ru': 'Сен-Пьер и Микелон',
      },
      languageCodes: ['fr', 'en'],
    ),
    CountryConfig(
  code: 'PN',
  alpha3: 'PCN',
  numericCode: '612',
  names: {
    'zh': '皮特凯恩群岛',
    'en': 'Pitcairn Islands',
    'ms': 'Kepulauan Pitcairn',
    'vi': 'Quần đảo Pitcairn',
    'ru': 'о-ва Питкэрн',
  },
  languageCodes: ['en'],
),
    CountryConfig(
      code: 'PR',
      alpha3: 'PRI',
      numericCode: '630',
      names: {
        'zh': '波多黎各',
        'en': 'Puerto Rico',
        'ms': 'Puerto Rico',
        'vi': 'Puerto Rico',
        'ru': 'Пуэрто-Рико',
      },
      languageCodes: ['es', 'en'],
    ),
    CountryConfig(
      code: 'PS',
      alpha3: 'PSE',
      numericCode: '275',
      names: {
        'zh': '巴勒斯坦领土',
        'en': 'Palestinian Territories',
        'ms': 'Wilayah Palestin',
        'vi': 'Lãnh thổ Palestine',
        'ru': 'Палестинские территории',
      },
      languageCodes: ['ar'],
    ),
    CountryConfig(
      code: 'PT',
      alpha3: 'PRT',
      numericCode: '620',
      names: {
        'zh': '葡萄牙',
        'en': 'Portugal',
        'ms': 'Portugal',
        'vi': 'Bồ Đào Nha',
        'ru': 'Португалия',
      },
      languageCodes: ['pt', 'en', 'fr', 'es', 'gl'],
    ),
    CountryConfig(
      code: 'PW',
      alpha3: 'PLW',
      numericCode: '585',
      names: {
        'zh': '帕劳',
        'en': 'Palau',
        'ms': 'Palau',
        'vi': 'Palau',
        'ru': 'Палау',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'PY',
      alpha3: 'PRY',
      numericCode: '600',
      names: {
        'zh': '巴拉圭',
        'en': 'Paraguay',
        'ms': 'Paraguay',
        'vi': 'Paraguay',
        'ru': 'Парагвай',
      },
      languageCodes: ['gn', 'es', 'de'],
    ),
    CountryConfig(
      code: 'QA',
      alpha3: 'QAT',
      numericCode: '634',
      names: {
        'zh': '卡塔尔',
        'en': 'Qatar',
        'ms': 'Qatar',
        'vi': 'Qatar',
        'ru': 'Катар',
      },
      languageCodes: ['ar', 'fa', 'ml'],
    ),
    CountryConfig(
      code: 'RE',
      alpha3: 'REU',
      numericCode: '638',
      names: {
        'zh': '留尼汪',
        'en': 'Réunion',
        'ms': 'Reunion',
        'vi': 'Réunion',
        'ru': 'Реюньон',
      },
      languageCodes: ['fr', 'ta'],
    ),
    CountryConfig(
      code: 'RO',
      alpha3: 'ROU',
      numericCode: '642',
      names: {
        'zh': '罗马尼亚',
        'en': 'Romania',
        'ms': 'Romania',
        'vi': 'Romania',
        'ru': 'Румыния',
      },
      languageCodes: [
        'ro',
        'en',
        'fr',
        'es',
        'hu',
        'de',
        'tr',
        'sr',
        'el',
        'pl',
      ],
    ),
    CountryConfig(
      code: 'RS',
      alpha3: 'SRB',
      numericCode: '688',
      names: {
        'zh': '塞尔维亚',
        'en': 'Serbia',
        'ms': 'Serbia',
        'vi': 'Serbia',
        'ru': 'Сербия',
      },
      languageCodes: ['sr', 'hu', 'ro', 'hr', 'sk', 'uk'],
    ),
    CountryConfig(
      code: 'RU',
      alpha3: 'RUS',
      numericCode: '643',
      names: {
        'zh': '俄罗斯',
        'en': 'Russia',
        'ms': 'Rusia',
        'vi': 'Nga',
        'ru': 'Россия',
      },
      languageCodes: ['ru', 'hy', 'fi'],
    ),
    CountryConfig(
      code: 'RW',
      alpha3: 'RWA',
      numericCode: '646',
      names: {
        'zh': '卢旺达',
        'en': 'Rwanda',
        'ms': 'Rwanda',
        'vi': 'Rwanda',
        'ru': 'Руанда',
      },
      languageCodes: ['rw', 'en', 'fr'],
    ),
    CountryConfig(
      code: 'SA',
      alpha3: 'SAU',
      numericCode: '682',
      names: {
        'zh': '沙特阿拉伯',
        'en': 'Saudi Arabia',
        'ms': 'Arab Saudi',
        'vi': 'Ả Rập Xê-út',
        'ru': 'Саудовская Аравия',
      },
      languageCodes: ['ar'],
    ),
    CountryConfig(
      code: 'SB',
      alpha3: 'SLB',
      numericCode: '090',
      names: {
        'zh': '所罗门群岛',
        'en': 'Solomon Islands',
        'ms': 'Kepulauan Solomon',
        'vi': 'Quần đảo Solomon',
        'ru': 'Соломоновы о-ва',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'SC',
      alpha3: 'SYC',
      numericCode: '690',
      names: {
        'zh': '塞舌尔',
        'en': 'Seychelles',
        'ms': 'Seychelles',
        'vi': 'Seychelles',
        'ru': 'Сейшельские о-ва',
      },
      languageCodes: ['fr', 'en'],
    ),
    CountryConfig(
      code: 'SD',
      alpha3: 'SDN',
      numericCode: '729',
      names: {
        'zh': '苏丹',
        'en': 'Sudan',
        'ms': 'Sudan',
        'vi': 'Sudan',
        'ru': 'Судан',
      },
      languageCodes: ['ar', 'en', 'ha'],
    ),
    CountryConfig(
      code: 'SE',
      alpha3: 'SWE',
      numericCode: '752',
      names: {
        'zh': '瑞典',
        'en': 'Sweden',
        'ms': 'Sweden',
        'vi': 'Thụy Điển',
        'ru': 'Швеция',
      },
      languageCodes: ['sv', 'fi', 'en', 'yi'],
    ),
    CountryConfig(
      code: 'SG',
      alpha3: 'SGP',
      numericCode: '702',
      names: {
        'zh': '新加坡',
        'en': 'Singapore',
        'ms': 'Singapura',
        'vi': 'Singapore',
        'ru': 'Сингапур',
      },
      languageCodes: ['en', 'zh', 'ms', 'ta', 'ml', 'pa'],
    ),
    CountryConfig(
      code: 'SH',
      alpha3: 'SHN',
      numericCode: '654',
      names: {
        'zh': '圣赫勒拿',
        'en': 'St. Helena',
        'ms': 'Saint Helena',
        'vi': 'St. Helena',
        'ru': 'о-в Св. Елены',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'SI',
      alpha3: 'SVN',
      numericCode: '705',
      names: {
        'zh': '斯洛文尼亚',
        'en': 'Slovenia',
        'ms': 'Slovenia',
        'vi': 'Slovenia',
        'ru': 'Словения',
      },
      languageCodes: ['sl', 'hr', 'en', 'de', 'hu', 'it'],
    ),
    CountryConfig(
      code: 'SJ',
      alpha3: 'SJM',
      numericCode: '744',
      names: {
        'zh': '斯瓦尔巴和扬马延',
        'en': 'Svalbard & Jan Mayen',
        'ms': 'Svalbard dan Jan Mayen',
        'vi': 'Svalbard và Jan Mayen',
        'ru': 'Шпицберген и Ян-Майен',
      },
      languageCodes: ['no', 'ru'],
    ),
    CountryConfig(
      code: 'SK',
      alpha3: 'SVK',
      numericCode: '703',
      names: {
        'zh': '斯洛伐克',
        'en': 'Slovakia',
        'ms': 'Slovakia',
        'vi': 'Slovakia',
        'ru': 'Словакия',
      },
      languageCodes: ['sk', 'cs', 'en', 'de', 'hu', 'uk', 'pl'],
    ),
    CountryConfig(
      code: 'SL',
      alpha3: 'SLE',
      numericCode: '694',
      names: {
        'zh': '塞拉利昂',
        'en': 'Sierra Leone',
        'ms': 'Sierra Leone',
        'vi': 'Sierra Leone',
        'ru': 'Сьерра-Леоне',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'SM',
      alpha3: 'SMR',
      numericCode: '674',
      names: {
        'zh': '圣马力诺',
        'en': 'San Marino',
        'ms': 'San Marino',
        'vi': 'San Marino',
        'ru': 'Сан-Марино',
      },
      languageCodes: ['it', 'eo'],
    ),
    CountryConfig(
      code: 'SN',
      alpha3: 'SEN',
      numericCode: '686',
      names: {
        'zh': '塞内加尔',
        'en': 'Senegal',
        'ms': 'Senegal',
        'vi': 'Senegal',
        'ru': 'Сенегал',
      },
      languageCodes: ['fr', 'wo'],
    ),
    CountryConfig(
      code: 'SO',
      alpha3: 'SOM',
      numericCode: '706',
      names: {
        'zh': '索马里',
        'en': 'Somalia',
        'ms': 'Somalia',
        'vi': 'Somalia',
        'ru': 'Сомали',
      },
      languageCodes: ['so', 'ar', 'sw'],
    ),
    CountryConfig(
      code: 'SR',
      alpha3: 'SUR',
      numericCode: '740',
      names: {
        'zh': '苏里南',
        'en': 'Suriname',
        'ms': 'Surinam',
        'vi': 'Suriname',
        'ru': 'Суринам',
      },
      languageCodes: ['nl', 'zh'],
    ),
    CountryConfig(
      code: 'SS',
      alpha3: 'SSD',
      numericCode: '728',
      names: {
        'zh': '南苏丹',
        'en': 'South Sudan',
        'ms': 'Sudan Selatan',
        'vi': 'Nam Sudan',
        'ru': 'Южный Судан',
      },
      languageCodes: ['en', 'ar'],
    ),
    CountryConfig(
      code: 'ST',
      alpha3: 'STP',
      numericCode: '678',
      names: {
        'zh': '圣多美和普林西比',
        'en': 'São Tomé & Príncipe',
        'ms': 'Sao Tome dan Principe',
        'vi': 'São Tomé và Príncipe',
        'ru': 'Сан-Томе и Принсипи',
      },
      languageCodes: ['pt', 'fr'],
    ),
    CountryConfig(
      code: 'SV',
      alpha3: 'SLV',
      numericCode: '222',
      names: {
        'zh': '萨尔瓦多',
        'en': 'El Salvador',
        'ms': 'El Salvador',
        'vi': 'El Salvador',
        'ru': 'Сальвадор',
      },
      languageCodes: ['es'],
    ),
    CountryConfig(
      code: 'SX',
      alpha3: 'SXM',
      numericCode: '534',
      names: {
        'zh': '荷属圣马丁',
        'en': 'Sint Maarten',
        'ms': 'Sint Maarten',
        'vi': 'Sint Maarten',
        'ru': 'Синт-Мартен',
      },
      languageCodes: ['en', 'nl', 'es'],
    ),
    CountryConfig(
      code: 'SY',
      alpha3: 'SYR',
      numericCode: '760',
      names: {
        'zh': '叙利亚',
        'en': 'Syria',
        'ms': 'Syria',
        'vi': 'Syria',
        'ru': 'Сирия',
      },
      languageCodes: ['ar', 'ku', 'fr', 'hy'],
    ),
    CountryConfig(
      code: 'SZ',
      alpha3: 'SWZ',
      numericCode: '748',
      names: {
        'zh': '斯威士兰',
        'en': 'Eswatini',
        'ms': 'Eswatini',
        'vi': 'Eswatini',
        'ru': 'Эсватини',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'TC',
      alpha3: 'TCA',
      numericCode: '796',
      names: {
        'zh': '特克斯和凯科斯群岛',
        'en': 'Turks & Caicos Islands',
        'ms': 'Kepulauan Turks dan Caicos',
        'vi': 'Quần đảo Turks và Caicos',
        'ru': 'Тёркс и Кайкос',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'TD',
      alpha3: 'TCD',
      numericCode: '148',
      names: {
        'zh': '乍得',
        'en': 'Chad',
        'ms': 'Chad',
        'vi': 'Chad',
        'ru': 'Чад',
      },
      languageCodes: ['ar', 'fr'],
    ),
    CountryConfig(
      code: 'TF',
      alpha3: 'ATF',
      numericCode: '260',
      names: {
        'zh': '法属南部领地',
        'en': 'French Southern Territories',
        'ms': 'Wilayah Selatan Perancis',
        'vi': 'Lãnh thổ phía Nam Thuộc Pháp',
        'ru': 'Французские Южные территории',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'TG',
      alpha3: 'TGO',
      numericCode: '768',
      names: {
        'zh': '多哥',
        'en': 'Togo',
        'ms': 'Togo',
        'vi': 'Togo',
        'ru': 'Того',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'TH',
      alpha3: 'THA',
      numericCode: '764',
      names: {
        'zh': '泰国',
        'en': 'Thailand',
        'ms': 'Thailand',
        'vi': 'Thái Lan',
        'ru': 'Таиланд',
      },
      languageCodes: ['th', 'en', 'zh'],
    ),
    CountryConfig(
      code: 'TJ',
      alpha3: 'TJK',
      numericCode: '762',
      names: {
        'zh': '塔吉克斯坦',
        'en': 'Tajikistan',
        'ms': 'Tajikistan',
        'vi': 'Tajikistan',
        'ru': 'Таджикистан',
      },
      languageCodes: ['tg', 'ru', 'fa', 'ar'],
    ),
    CountryConfig(
      code: 'TK',
      alpha3: 'TKL',
      numericCode: '772',
      names: {
        'zh': '托克劳',
        'en': 'Tokelau',
        'ms': 'Tokelau',
        'vi': 'Tokelau',
        'ru': 'Токелау',
      },
      languageCodes: ['en', 'sm'],
    ),
    CountryConfig(
      code: 'TL',
      alpha3: 'TLS',
      numericCode: '626',
      names: {
        'zh': '东帝汶',
        'en': 'Timor-Leste',
        'ms': 'Timor-Leste',
        'vi': 'Timor-Leste',
        'ru': 'Восточный Тимор',
      },
      languageCodes: ['pt'],
    ),
    CountryConfig(
      code: 'TM',
      alpha3: 'TKM',
      numericCode: '795',
      names: {
        'zh': '土库曼斯坦',
        'en': 'Turkmenistan',
        'ms': 'Turkmenistan',
        'vi': 'Turkmenistan',
        'ru': 'Туркменистан',
      },
      languageCodes: ['tk', 'ru', 'uz', 'ku'],
    ),
    CountryConfig(
      code: 'TN',
      alpha3: 'TUN',
      numericCode: '788',
      names: {
        'zh': '突尼斯',
        'en': 'Tunisia',
        'ms': 'Tunisia',
        'vi': 'Tunisia',
        'ru': 'Тунис',
      },
      languageCodes: ['ar', 'fr'],
    ),
    CountryConfig(
      code: 'TO',
      alpha3: 'TON',
      numericCode: '776',
      names: {
        'zh': '汤加',
        'en': 'Tonga',
        'ms': 'Tonga',
        'vi': 'Tonga',
        'ru': 'Тонга',
      },
      languageCodes: ['to', 'en'],
    ),
    CountryConfig(
      code: 'TR',
      alpha3: 'TUR',
      numericCode: '792',
      names: {
        'zh': '土耳其',
        'en': 'Türkiye',
        'ms': 'Turkiye',
        'vi': 'Thổ Nhĩ Kỳ',
        'ru': 'Турция',
      },
      languageCodes: ['tr', 'en', 'ku', 'ar', 'hy', 'ka', 'sr'],
    ),
    CountryConfig(
      code: 'TT',
      alpha3: 'TTO',
      numericCode: '780',
      names: {
        'zh': '特立尼达和多巴哥',
        'en': 'Trinidad & Tobago',
        'ms': 'Trinidad dan Tobago',
        'vi': 'Trinidad và Tobago',
        'ru': 'Тринидад и Тобаго',
      },
      languageCodes: ['en', 'es'],
    ),
    CountryConfig(
      code: 'TV',
      alpha3: 'TUV',
      numericCode: '798',
      names: {
        'zh': '图瓦卢',
        'en': 'Tuvalu',
        'ms': 'Tuvalu',
        'vi': 'Tuvalu',
        'ru': 'Тувалу',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'TW',
      alpha3: 'TWN',
      numericCode: '158',
      names: {
        'zh': '台湾',
        'en': 'Taiwan',
        'ms': 'Taiwan',
        'vi': 'Đài Loan',
        'ru': 'Тайвань',
      },
      languageCodes: ['zh'],
    ),
    CountryConfig(
      code: 'TZ',
      alpha3: 'TZA',
      numericCode: '834',
      names: {
        'zh': '坦桑尼亚',
        'en': 'Tanzania',
        'ms': 'Tanzania',
        'vi': 'Tanzania',
        'ru': 'Танзания',
      },
      languageCodes: ['sw', 'en'],
    ),
    CountryConfig(
      code: 'UA',
      alpha3: 'UKR',
      numericCode: '804',
      names: {
        'zh': '乌克兰',
        'en': 'Ukraine',
        'ms': 'Ukraine',
        'vi': 'Ukraina',
        'ru': 'Украина',
      },
      languageCodes: ['uk', 'ru', 'pl', 'yi', 'ro', 'tr', 'hu', 'el'],
    ),
    CountryConfig(
      code: 'UG',
      alpha3: 'UGA',
      numericCode: '800',
      names: {
        'zh': '乌干达',
        'en': 'Uganda',
        'ms': 'Uganda',
        'vi': 'Uganda',
        'ru': 'Уганда',
      },
      languageCodes: ['sw', 'en', 'rw'],
    ),
    CountryConfig(
      code: 'UM',
      alpha3: 'UMI',
      numericCode: '581',
      names: {
        'zh': '美国本土外小岛屿',
        'en': 'U.S. Outlying Islands',
        'ms': 'Kepulauan Terpencil A.S.',
        'vi': 'Các tiểu đảo xa của Hoa Kỳ',
        'ru': 'Внешние малые о-ва (США)',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'US',
      alpha3: 'USA',
      numericCode: '840',
      names: {
        'zh': '美国',
        'en': 'United States',
        'ms': 'Amerika Syarikat',
        'vi': 'Hoa Kỳ',
        'ru': 'Соединенные Штаты',
      },
      languageCodes: [
        'en',
        'es',
        'haw',
        'zh',
        'fr',
        'de',
        'tl',
        'it',
        'vi',
        'ko',
        'ru',
        'nv',
        'yi',
        'chr',
      ],
    ),
    CountryConfig(
      code: 'UY',
      alpha3: 'URY',
      numericCode: '858',
      names: {
        'zh': '乌拉圭',
        'en': 'Uruguay',
        'ms': 'Uruguay',
        'vi': 'Uruguay',
        'ru': 'Уругвай',
      },
      languageCodes: ['es'],
    ),
    CountryConfig(
      code: 'UZ',
      alpha3: 'UZB',
      numericCode: '860',
      names: {
        'zh': '乌兹别克斯坦',
        'en': 'Uzbekistan',
        'ms': 'Uzbekistan',
        'vi': 'Uzbekistan',
        'ru': 'Узбекистан',
      },
      languageCodes: ['uz', 'ru', 'tr'],
    ),
    CountryConfig(
      code: 'VA',
      alpha3: 'VAT',
      numericCode: '336',
      names: {
        'zh': '梵蒂冈',
        'en': 'Vatican City',
        'ms': 'Kota Vatican',
        'vi': 'Thành Vatican',
        'ru': 'Ватикан',
      },
      languageCodes: ['it', 'la'],
    ),
    CountryConfig(
      code: 'VC',
      alpha3: 'VCT',
      numericCode: '670',
      names: {
        'zh': '圣文森特和格林纳丁斯',
        'en': 'St. Vincent & Grenadines',
        'ms': 'Saint Vincent dan Grenadines',
        'vi': 'St. Vincent và Grenadines',
        'ru': 'Сент-Винсент и Гренадины',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'VE',
      alpha3: 'VEN',
      numericCode: '862',
      names: {
        'zh': '委内瑞拉',
        'en': 'Venezuela',
        'ms': 'Venezuela',
        'vi': 'Venezuela',
        'ru': 'Венесуэла',
      },
      languageCodes: ['es'],
    ),
    CountryConfig(
      code: 'VG',
      alpha3: 'VGB',
      numericCode: '092',
      names: {
        'zh': '英属维尔京群岛',
        'en': 'British Virgin Islands',
        'ms': 'Kepulauan Virgin British',
        'vi': 'Quần đảo Virgin thuộc Anh',
        'ru': 'Виргинские о-ва (Великобритания)',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'VI',
      alpha3: 'VIR',
      numericCode: '850',
      names: {
        'zh': '美属维尔京群岛',
        'en': 'U.S. Virgin Islands',
        'ms': 'Kepulauan Virgin A.S.',
        'vi': 'Quần đảo Virgin thuộc Hoa Kỳ',
        'ru': 'Виргинские о-ва (США)',
      },
      languageCodes: ['en'],
    ),
    CountryConfig(
      code: 'VN',
      alpha3: 'VNM',
      numericCode: '704',
      names: {
        'zh': '越南',
        'en': 'Vietnam',
        'ms': 'Vietnam',
        'vi': 'Việt Nam',
        'ru': 'Вьетнам',
      },
      languageCodes: ['vi', 'zh'],
    ),
    CountryConfig(
      code: 'VU',
      alpha3: 'VUT',
      numericCode: '548',
      names: {
        'zh': '瓦努阿图',
        'en': 'Vanuatu',
        'ms': 'Vanuatu',
        'vi': 'Vanuatu',
        'ru': 'Вануату',
      },
      languageCodes: ['en', 'fr'],
    ),
    CountryConfig(
      code: 'WF',
      alpha3: 'WLF',
      numericCode: '876',
      names: {
        'zh': '瓦利斯和富图纳',
        'en': 'Wallis & Futuna',
        'ms': 'Wallis dan Futuna',
        'vi': 'Wallis và Futuna',
        'ru': 'Уоллис и Футуна',
      },
      languageCodes: ['fr'],
    ),
    CountryConfig(
      code: 'WS',
      alpha3: 'WSM',
      numericCode: '882',
      names: {
        'zh': '萨摩亚',
        'en': 'Samoa',
        'ms': 'Samoa',
        'vi': 'Samoa',
        'ru': 'Самоа',
      },
      languageCodes: ['sm', 'en'],
    ),
    CountryConfig(
      code: 'YE',
      alpha3: 'YEM',
      numericCode: '887',
      names: {
        'zh': '也门',
        'en': 'Yemen',
        'ms': 'Yaman',
        'vi': 'Yemen',
        'ru': 'Йемен',
      },
      languageCodes: ['ar', 'en'],
    ),
    CountryConfig(
      code: 'YT',
      alpha3: 'MYT',
      numericCode: '175',
      names: {
        'zh': '马约特',
        'en': 'Mayotte',
        'ms': 'Mayotte',
        'vi': 'Mayotte',
        'ru': 'Майотта',
      },
      languageCodes: ['fr', 'sw'],
    ),
    CountryConfig(
      code: 'ZA',
      alpha3: 'ZAF',
      numericCode: '710',
      names: {
        'zh': '南非',
        'en': 'South Africa',
        'ms': 'Afrika Selatan',
        'vi': 'Nam Phi',
        'ru': 'Южно-Африканская Республика',
      },
      languageCodes: ['en', 'af', 'tn', 'st', 'hi'],
    ),
    CountryConfig(
      code: 'ZM',
      alpha3: 'ZMB',
      numericCode: '894',
      names: {
        'zh': '赞比亚',
        'en': 'Zambia',
        'ms': 'Zambia',
        'vi': 'Zambia',
        'ru': 'Замбия',
      },
      languageCodes: ['en', 'ny'],
    ),
    CountryConfig(
      code: 'ZW',
      alpha3: 'ZWE',
      numericCode: '716',
      names: {
        'zh': '津巴布韦',
        'en': 'Zimbabwe',
        'ms': 'Zimbabwe',
        'vi': 'Zimbabwe',
        'ru': 'Зимбабве',
      },
      languageCodes: ['en', 'ny', 'tn'],
    ),
  ];
}
